#!/bin/bash

### BEGIN INIT INFO
# Provides:          gd-dyn-dns
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GoDaddy Dynamic DNS Service
# Description:       This service is used to manage DNS via GoDaddy Dynamic DNS Service for dynamic IP's
### END INIT INFO

# Some things that run always
touch /var/lock/gd-dyn-dns

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/etc/gd-dyn-dns
DAEMON="$DIR/godaddy.py"
DAEMON_NAME="gd-dyn-dns"

# Add any command line options for your daemon here
DAEMON_OPTS=">> /var/log/$DAEMON_NAME/out.log 2>&1"

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid


. /lib/lsb/init-functions

do_start () {
        if [[ $(ps -ef | grep -c "python $DAEMON")  -ne 1 ]]; then
                echo "$DAEMON_NAME service is already running!"
        else
                echo "Starting $DAEMON_NAME service"
                su -l $DEAMON_USER -c "python $DAEMON $DAEMON_OPTS &"
                echo "...[OK]"
        fi
}
do_stop () {
        echo "Stopping $DAEMON_NAME service"
        pkill -1 -f $DAEMON
        echo "...[OK]"
}

# Carry out specific functions when asked to by the system
case "$1" in
        start|stop)
                do_${1}
        ;;
        status)
                if [[ $(ps -ef | grep -c "python $DAEMON")  -ne 1 ]]; then
                        echo "$DAEMON_NAME service is running!"
                else
                        echo "$DAEMON_NAME service not running!"
                fi
                #status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
        restart)
                do_stop
                do_start
        ;;
        *)
                echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop}"
                exit 1
                ;;
esac

exit 0